spring:
  redis:
    host: 192.168.43.209
    port: 6379
  rabbitmq:
    host: 192.168.43.209
    port: 5672
    username: guest
    password: guest
zuul:
  #忽略全部服务敏感头（全部服务都可传递cookie）
  sensitive-headers: 
  routes:
  # /myProduct/product/list -> /product/product/list
    myProduct:
      path: /myProduct/**
      serviceId: product
      sensitiveHeaders:
  # 简洁写法
#    product: /myProduct/**
  # 排除某些路由
  ignored-patterns:
    - /**/product/listForOrder
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
ribbon:
  ReadTimeout: 5000
  SocketTimeout: 5000
