spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.43.43:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
  redis:
    host: 192.168.43.209
    port: 6379
  rabbitmq:
    host: 192.168.43.209
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
feign:
  hystrix:
    enable: true
management:
  context-path: /
# 把 org.springframework.cloud.netflix.feign包 调整日志级别
logging:
  level:
    org.springframework.cloud.netflix.feign: debug
#用来设置feign超时，springcloud 1.0的版本没有这个设置
feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: basic
