spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.103:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
  redis:
    host: 192.168.1.104
    port: 6379
  rabbitmq:
    host: 192.168.1.104
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1
  jpa:
    show-sql: true
