spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.43.43:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
  redis:
    host: 192.168.43.209
    port: 6379
  rabbitmq:
    host: 192.168.43.209
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://192.168.43.209:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  jpa:
    show-sql: true
